= Asciidoc Nintendo eShop Project

This is a project proposal for a Nintendo eShop under the next conditions:

El proyecto consiste en planificar una p谩gina Ecommerce. El alumno debe entregar un informe creado con Asciidoc que contenga las siguientes caracter铆sticas:

- Selecci贸n de Servidor.
- Dise帽o de base de datos.
- Dise帽o de endpoint Rest.
- Estimaci贸n de Costos de Servidor y Operaci贸n.
- Selecci贸n Tecnol贸gica Backend (驴CMS o custom?).
- Selecci贸n Tecnol贸gica Frontend.
- Selecci贸n de Profesionales necesarios.
- Estimaci贸n de Plazos para implementar.


== Technology

- https://www.docker.com/
- https://docs.asciidoctor.org/
- Python3 (Webserver)
- https://pandoc.org/ (Conversion to multiple formats)

=== Diagrams

Using the base Dockerfile for https://docs.asciidoctor.org/diagram-extension/latest/

The following technologies were selected for diagrams:

- https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/plantuml/[PlantUML]: UML diagrams and C4 architecture diagrams.
- https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/graphviz/[Graphviz]: Generic diagrams tool.
- https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/dbml/[DBML]: Database ERD diagrams (friendlier syntax than PlantUML)
- https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/vega/[Vega]: Declarative language for creating, saving, and sharing interactive visualization designs.

.WIP Diagrams
These need extra configurations inside the Dockerfile to Work (Puppeteer).

- https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/mermaid/[Mermaid]: Uses Markdown-inspired text definitions and a renderer to create and modify complex diagrams.
- https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/bpmn/[BMPN]: Business Process Model and Notation.

== Commands

- `make install`: Builds the Dockerfile.
- `make html`: Builds the html version of the book.
- `make pdf`: Builds a PDF version of the book.
- `make server`: Starts a new server for the html version. (requires python3).
- `make word`: Creates a new Microsoft Word document from the book. (requires pandoc).

== License

Project made by Diana Narvaez.

Template created with わ by https://ninjas.cl[Camilo Castro] and https://github.com/ninjascl/asciidoc-book-template/graphs/contributors[contributors]footnote:[https://github.com/ninjascl/asciidoc-book-template/graphs/contributors]. for https://ninjas.cl[Ninjas.cl]{fn-ninjas}.

This document is licensed with http://creativecommons.org/licenses/by-nc-sa/4.0/[Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International]footnote:[http://creativecommons.org/licenses/by-nc-sa/4.0/]

http://creativecommons.org/licenses/by-nc-sa/4.0/[image:resources/images/by-nc-sa.svg[Licencia Creative Commons]]

Source code licensed with https://opensource.org/licenses/BSD-2-Clause[BSD-2]footnote:[https://opensource.org/licenses/BSD-2-Clause].

## ぉ Credits

++++
<p>
  Made with <i class="fa fa-heart">&#9829;</i> by
  <a href="https://ninjas.cl">
    Ninjas.cl
  </a>.
</p>
++++
